### ISSUE TITLE
Detection of GMPlib fails on mac os X

### ISSUE THREAD

**Issue by pehrsoderman** [Kattis/problemtools#52]
Encountered when installing. Here is the log: 

```
Snowcrash:~ pehrs$ pip install git+https://github.com/kattis/problemtools
Collecting git+https://github.com/kattis/problemtools
  Cloning https://github.com/kattis/problemtools to /var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-E13lxc-build
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python2.7/site-packages (from problemtools===v1.20160728-7-g0b9f432)
Requirement already satisfied (use --upgrade to upgrade): plasTeX in /usr/local/lib/python2.7/site-packages (from problemtools===v1.20160728-7-g0b9f432)
Installing collected packages: problemtools
  Running setup.py install for problemtools ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-E13lxc-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-05JcaC-record/install-record.txt --single-version-externally-managed --compile:
    readlink: illegal option -- f
    usage: readlink [-n] [file ...]
    /usr/local/lib/python2.7/site-packages/setuptools/dist.py:294: UserWarning: The version specified ('v1.20160728-7-g0b9f432') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    running install
    running build
    running build_support
    Running command: make -C support install DESTDIR=/private/var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-E13lxc-build/build/lib/problemtools/support
    cd checktestdata && ./bootstrap
    + set -e
    + aclocal -I m4
    + autoconf
    + ./configure --disable-parsergeneration
    checking whether configure should try to set CFLAGS... yes
    checking whether configure should try to set CXXFLAGS... yes
    checking whether configure should try to set LDFLAGS... yes
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether C compiler accepts -Wall... yes
    checking whether C compiler accepts -fstack-protector... yes
    checking whether C compiler accepts -fPIE... yes
    checking whether C compiler accepts -D_FORTIFY_SOURCE=2... yes
    checking whether the linker accepts -fPIE... yes
    checking whether the linker accepts -pie... yes
    checking whether the linker accepts -Wl,-z,relro... no
    checking whether the linker accepts -Wl,-z,now... no
    checking for g++... g++
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking for gcc... (cached) gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking how to run the C++ preprocessor... g++ -E
    checking how to run the C preprocessor... gcc -E
    checking build system type... x86_64-apple-darwin15.6.0
    checking host system type... x86_64-apple-darwin15.6.0
    checking for boostlib >= 1.33.1... yes
    checking whether the Boost::Regex library is available... yes
    checking for exit in -lboost_regex-mt... yes
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking gmpxx.h usability... no
    checking gmpxx.h presence... no
    checking for gmpxx.h... no
    checking for abs in -lgmpxx... no
    configure: error: GMPlib not found
    make: *** [checktestdata/config.mk] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-E13lxc-build/setup.py", line 94, in <module>
        'build': build
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-E13lxc-build/setup.py", line 44, in run
        self.run_command('build_support')
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-E13lxc-build/setup.py", line 29, in run
        subprocess.check_call(command)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-C', 'support', 'install', 'DESTDIR=/private/var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-E13lxc-build/build/lib/problemtools/support']' returned non-zero exit status 2

    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-E13lxc-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-05JcaC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/tg/vk556qn144jcxzgjdgrk79yw0000gn/T/pip-E13lxc-build/
Snowcrash:~ pehrs$ brew search gmp
gmp ✔
homebrew/php/php53-gmp                 homebrew/php/php54-gmp                 homebrew/php/php55-gmp                 homebrew/php/php56-gmp                 homebrew/php/php70-gmp                 homebrew/php/php71-gmp                 homebrew/versions/gmp4               
Snowcrash:~ pehrs$ locate gmpxx.h
/usr/local/Cellar/gmp/5.1.3/include/gmpxx.h
/usr/local/Cellar/gmp/6.0.0a/include/gmpxx.h
/usr/local/include/gmpxx.h
```

**Comment by eldering** [comment]
@pehrsoderman This is probably a bug/issue in [checktestdata](https://github.com/DOMjudge/checktestdata) itself. Could you provide the `config.log` file from checktestdata after running `configure`?
I have no experience with OS X, is `/usr/local/Cellar` a normal place to store header files?

**Comment by pehrsoderman** [comment]
`/usr/local/Cellar` is part of the homebrew system, so the path is not unusual for custom packages on Mac OS X. Have attached the [config.log](https://github.com/Kattis/problemtools/files/592878/config.log.txt) as well.

**Comment by eldering** [comment]
I think the problem is that your compiler (LLVM clang posing as GCC) doesn't have `/usr/local/Cellar` configured as an include dir. You should be able to check this with
```
clang++ -E -x c++ - -v < /dev/null
```
If that doesn't work, you can try to explicitly add it to your path via the `CPPFLAGS` variable, 
`export CPPFLAGS=-I/usr/local/Cellar` and then run `pip install` or directly `configure` in checktestdata.
See also:
http://stackoverflow.com/questions/28079143/boost-headers-not-found-issue-in-mac-os-x
http://stackoverflow.com/questions/19852199/view-default-include-path-of-c-headers-in-mac-os-x-by-gcc-v

**Comment by austrin** [comment]
@pehrsoderman did @eldering's suggestion work?

**Comment by pehrsoderman** [comment]
Well...

`export CPPFLAGS='-I/usr/local/include/ -L/usr/local/lib/'`

Makes the build system detect GMPLib correctly on the Mac, only to have things break a few lines further down: 

```
checking for bisonc++... ./configure: line 5783: bisonc++: command not found
configure: error: bisonc++ not found (required for dist build)
```

As far as I can tell, bisonc++ is not standard on the mac, not packaged in homebrew and while i found somebody who had packaged it (http://jpvanoosten.nl/blog/2011/07/23/fbb-software-bobcat-bisoncpp-on-the-mac/), those packages are so outdated that they can't be installed.

**Comment by austrin** [comment]
@pehrsoderman bisonc++ should not be required.  However, it was required for a few commits while the checktestdata submodule was pointing at the wrong commit.  Which commit of problemtools did you run on?

**Comment by pehrsoderman** [comment]
I cleaned everything and started over. After updating pip to 9.0.1 I got problemtools to install.

A manual make in support still breaks like this: 

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C checktestdata; /Applications/Xcode.app/Contents/Developer/usr/bin/make -C default_validator; /Applications/Xcode.app/Contents/Developer/usr/bin/make -C interactive;
g++ -std=c++11 -g -O2 -Wall -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -std=c++11 -DVERSION="\"20170206\"" -I/usr/local/include/ -L/usr/local/lib/ -I/usr/local/include  -c -o libchecktestdata.o libchecktestdata.cc
clang: warning: argument unused during compilation: '-L/usr/local/lib/'
libchecktestdata.cc:1100:22: error: calling a private constructor of class 'std::__1::__wrap_iter<const char *>'
                if ( !regex_search((string::const_iterator)&data[datanr],
                                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:1239:31: note: declared private here
    _LIBCPP_INLINE_VISIBILITY __wrap_iter(iterator_type __x) _NOEXCEPT : __i(__x) {}
```

But it doesn't seem to prevent the installation of problemtools...? Compiler related perhaps?

**Comment by austrin** [comment]
@pehrsoderman great(ish)!  Without checktestdata you can still run problemtools but any checktestdata scripts will obviously not be working.  I think I'll close this now.

@eldering don't know if the last checktestdata compile error mentioned by Pehr (here: https://github.com/Kattis/problemtools/issues/52#issuecomment-277672562) is something you want to look at or not (I guess it's down to some version discrepancy).

**Comment by eldering** [comment]
I can find one reference to the same error: https://github.com/steakknife/tripwire/issues/1
Not sure this is a misuse of the STL on our side or a minor bug in the LLVM/osX libc++. I will have a closer look.
